---
full_load:
  - table: SalesReason
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: StateProvince
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: CountryRegion
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: SalesTaxRate
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: ShipMethod
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: SpecialOffer
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: User
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: UserAddress
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: UserCreditCard
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: SalesOrderHeader
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: SalesOrderHeaderSalesReason
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: SpecialOfferProduct
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: ShoppingCartItem
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: Currency
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: UserEmailAddress
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: CurrencyRate
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: SalesOrderDetail
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: TransactionAddress
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: SalesTerritory
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: UserPassword
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

delta_load:

 - table: User
   primary_keys:
    - UserID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: UserAddress
   primary_keys:
    - AddressID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: UserCreditCard
   primary_keys:
    - UserID
    - CreditCardID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: SalesOrderHeader
   primary_keys:
    - SalesOrderID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: SalesOrderHeaderSalesReason
   primary_keys:
    - SalesOrderID
    - SalesReasonID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: SpecialOfferProduct
   primary_keys:
    - SpecialOfferID
    - ProductID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: ShoppingCartItem
   primary_keys:
    - ShoppingCartItemID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~