---
full_load:
 - StackholderPosition
 - Department
 - PhoneNumberType
 - Shift
 - AddressType
 - SaleTerritoryRepHistory
 - SalesTerritory
 - CountryRegion
 - StateProvince

delta_load:

 - table: Stakeholder
   primary_keys:
    - StackHolderID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from {table} where (ModifiedDate > '{modifieddate}')
   delta_load_hql: SELECT MAX(MODIFIEDDATE) AS modifieddate FROM {hive_table}


