---
full_load:
 - StackholderPosition
 - Department
 - PhoneNumberType
 - Shift
 - AddressType
 - SaleTerritoryRepHistory
 - SalesTerritory
 - CountryRegion
 - StateProvince

delta_load:

 - table: Stackholder
   primary_keys:
    - StackHolderID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from Stackholder where (ModifiedDate > {modifieddate})
   delta_load_hql: SELECT MAX(MODIFIEDDATE) AS MODIFIEDDATE FROM {hive_table}

 - table: Employee
   primary_keys:
    - EmployeeID
   delta_keys:
    - ModifiedDate
   custom_load_sql: ~
   delta_load_hql: SELECT MAX(MODIFIEDDATE) AS MODIFIEDDATE FROM {hive_table}

