---
full_load:
  - table: StackholderPosition
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: Department
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: PhoneNumberType
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: Shift
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: AddressType
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: SaleTerritoryRepHistory
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: SalesTerritory
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: CountryRegion
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: StateProvince
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: Stakeholder
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: Employee
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: EmployeeDepartmentHistory
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: EmployeePayHistory
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: EmployeePhoneContact
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: JobCandidate
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: EmployeeAddress
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: Email
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: StackholderPassword
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: StackholderPhoneContact
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: SalePersons
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: SalesPersonQuotaHistory
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

delta_load:

 - table: Stakeholder
   primary_keys:
    - StackHolderID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: Employee
   primary_keys:
    - EmployeeID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: EmployeeDepartmentHistory
   primary_keys:
    - EmployeeID
    - DepartmentID
    - ShiftID
    - StartDate
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: EmployeePayHistory
   primary_keys:
    - EmployeeID
    - RateChangeDate
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: EmployeePhoneContact
   primary_keys:
    - EmployeeID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~
        
 - table: JobCandidate
   primary_keys:
    - JobCandidateID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: EmployeeAddress
   primary_keys:
    - EmployeeID
    - AddressID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: StackHolderEmail
   primary_keys:
    - StackHolderID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: EmployeeEmail
   primary_keys:
    - EmployeeID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: SalePersons
   primary_keys:
    - EmployeeID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: SalesPersonQuotaHistory
   primary_keys:
    - EmployeeID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~