---
full_load:
 - table: ProductCategory
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
 - table: ProductDocument
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
 - table: Document
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
    Document: CONVERT(NVARCHAR(MAX), [Document], 1)
 - table: ProductModel
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
 - table: ProductModelIllustration
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
 - table: Illustration
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
 - table: Culture
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
 - table: ProductSubcategory
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
 - table: UnitMeasure
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
 - table: ShipMethod
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
 - table: StateProvinceCountry
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
 - table: Location
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

delta_load:

 - table: Product
   primary_keys:
    - ProductID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: ProductCostHistory
   primary_keys:
    - ProductID
    - StartDate
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: ProductDescription
   primary_keys:
    - ProductDescriptionID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: ProductInventory
   primary_keys:
    - ProductID
    - LocationID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: ProductListPriceHistory
   primary_keys:
    - ProductID
    - StartDate
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: ProductModelProductDescriptionCulture
   primary_keys:
    - ProductModelID
    - ProductDescriptionID
    - CultureID
   delta_keys:
    - ModifiedDate
   custom_full_load_sql: Select * from {table} where (ModifiedDate > '{modifieddate}')e})
   delta_load_hql: |
        SELECT MAX(MODIFIEDDATE) AS modifieddate FROM {hive_table}

 - table: ProductPhoto
   primary_keys:
    - ProductPhotoID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: ProductProductPhoto
   primary_keys:
    - ProductID
    - ProductPhotoID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: ProductVendor
   primary_keys:
    - ProductID
    - VendorID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: ProductReview
   primary_keys:
    - ProductReviewID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: Vendor
   primary_keys:
    - VendorID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: VendorAddress
   primary_keys:
    - VendorID
    - AddressID
    - AddressTypeID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: WorkOrder
   primary_keys:
    - WorkOrderID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: WorkOrderRouting
   primary_keys:
    - WorkOrderID
    - ProductID
    - OperationSequence
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: BillOfMaterials
   primary_keys:
    - BillOfMaterialsID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: PurchaseOrderHeader
   primary_keys:
    - PurchaseOrderID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~

 - table: PurchaseOrderDetail
   primary_keys:
    - PurchaseOrderID
    - PurchaseOrderDetailID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
   custom_full_load_sql: ~
   custom_delta_load_sql: ~
   custom_deltakey_load_hql: ~