---
full_load:
 - ProductCategory
 - ProductDocument
 - Document
 - ProductModel
 - ProductModelIllustration
 - Illustration
 - Culture
 - ProductSubcategory
 - UnitMeasure
 - ShipMethod
 - StateProvinceCountry
 - Location


delta_load:

 - table: Product
   primary_keys:
    - ProductID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from Product where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: ProductCostHistory
   primary_keys:
    - ProductID
    - StartDate
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from ProductCostHistory where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: ProductDescription
   primary_keys:
    - ProductDescriptionID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from ProductDescription where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: ProductInventory
   primary_keys:
    - ProductID
    - LocationID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from ProductInventory where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: ProductListPriceHistory
   primary_keys:
    - ProductID
    - StartDate
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from ProductListPriceHistory where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: ProductModelProductDescriptionCulture
   primary_keys:
    - ProductModelID
    - ProductDescriptionID
    - CultureID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from ProductModelProductDescriptionCulture where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: ProductPhoto
   primary_keys:
    - ProductPhotoID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from ProductPhoto where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: ProductProductPhoto
   primary_keys:
    - ProductID
    - ProductPhotoID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from ProductProductPhoto where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: ProductVendor
   primary_keys:
    - ProductID
    - VendorID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from ProductVendor where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: Vendor
   primary_keys:
    - VendorID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from Vendor where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: VendorAddress
   primary_keys:
    - VendorID
    - AddressID
    - AddressTypeID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from VendorAddress where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: WorkOrder
   primary_keys:
    - WorkOrderID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from WorkOrder where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: WorkOrderRouting
   primary_keys:
    - WorkOrderID
    - ProductID
    - OperationSequence
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from WorkOrderRouting where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: BillOfMaterials
   primary_keys:
    - BillOfMaterialsID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from BillOfMaterials where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: PurchaseOrderHeader
   primary_keys:
    - PurchaseOrderID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from PurchaseOrderHeader where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}

 - table: PurchaseOrderDetail
   primary_keys:
    - PurchaseOrderID
    - PurchaseOrderDetailID
   delta_keys:
    - ModifiedDate
   custom_load_sql: Select * from PurchaseOrderDetail where (ModifiedDate > {modifieddate})
   delta_load_hql: |
        SELECT MAX(CAST(FROM_UNIXTIME(UNIX_TIMESTAMP(MODIFIEDDATE, 'MMM dd yyyy hh:mmaa')) AS TIMESTAMP)) 
        AS modifieddate 
        FROM {hive_table}