{{ config(materialized='view') }}

select 
    productid,
    name,
    productnumber,
    makeflag,
    finishedgoodsflag,
    color,
    safetystocklevel,
    reorderpoint,
    standardcost,
    listprice,
    size,                     	
    sizeunitmeasurecode,               	
    weightunitmeasurecode,              	
    weight,                            	
    daystomanufacture,                 	
    productline,
    class,
    style,      	
    productsubcategoryid,              	
    productmodelid,                    	
    sellstartdate,                     	
    sellenddate,                       	
    discontinueddate,
    modifieddate,
    is_deleted,
    date_partition
from {{ source("production", "product_management_platform_product") }}