AdventureWork:
  outputs:
   dev:
    type: spark
    method: thrift
    host: node01
    port: 10000
    user: hive
    schema: "{{ env_var('DW_SCHEMA') }}" 
    threads: 1 # Execute sequentially once per time due to the limitation on resource
  target: dev