---
full_load:
  - table: ProductCategory
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: ProductDocument
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: Document
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
      Document: CONVERT(NVARCHAR(MAX), [Document], 1)
  - table: ProductModel
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: ProductModelIllustration
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: Illustration
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: Culture
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: ProductSubcategory
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: UnitMeasure
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: ShipMethod
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: StateProvinceCountry
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  - table: Location
    custom_casts:
      ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: Product
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: ProductCostHistory
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: ProductDescription
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: ProductInventory
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: ProductListPriceHistory
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: ProductModelProductDescriptionCulture
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: ProductPhoto
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  #     ThumbNailPhoto: CONVERT(NVARCHAR(MAX), [ThumbNailPhoto], 1)
  #     LargePhoto: CONVERT(NVARCHAR(MAX), [LargePhoto], 1)
  # - table: ProductProductPhoto
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: ProductVendor
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: ProductReview
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: Vendor
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: VendorAddress
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: WorkOrder
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: WorkOrderRouting
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: BillOfMaterials
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: PurchaseOrderHeader
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: PurchaseOrderDetail
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: ContactType
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: VendorContact
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: ScrapReason
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: TransactionHistory
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  # - table: TransactionHistoryArchive
  #   custom_casts:
  #     ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

delta_load:

 - table: Product
   primary_keys:
    - ProductID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: ProductCostHistory
   primary_keys:
    - ProductID
    - StartDate
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: ProductDescription
   primary_keys:
    - ProductDescriptionID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: ProductInventory
   primary_keys:
    - ProductID
    - LocationID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: ProductListPriceHistory
   primary_keys:
    - ProductID
    - StartDate
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: ProductModelProductDescriptionCulture
   primary_keys:
    - ProductModelID
    - ProductDescriptionID
    - CultureID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: ProductPhoto
   primary_keys:
    - ProductPhotoID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
    ThumbNailPhoto: CONVERT(NVARCHAR(MAX), [ThumbNailPhoto], 1)
    LargePhoto: CONVERT(NVARCHAR(MAX), [LargePhoto], 1)

 - table: ProductProductPhoto
   primary_keys:
    - ProductID
    - ProductPhotoID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: ProductVendor
   primary_keys:
    - ProductID
    - VendorID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: ProductReview
   primary_keys:
    - ProductReviewID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: Vendor
   primary_keys:
    - VendorID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: VendorAddress
   primary_keys:
    - VendorID
    - AddressID
    - AddressTypeID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: WorkOrder
   primary_keys:
    - WorkOrderID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: WorkOrderRouting
   primary_keys:
    - WorkOrderID
    - ProductID
    - OperationSequence
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: BillOfMaterials
   primary_keys:
    - BillOfMaterialsID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: PurchaseOrderHeader
   primary_keys:
    - PurchaseOrderID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: PurchaseOrderDetail
   primary_keys:
    - PurchaseOrderID
    - PurchaseOrderDetailID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: ContactType
   primary_keys:
    - ContactTypeID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: VendorContact
   primary_keys:
    - VendorID
    - StackHolderID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: ScrapReason
   primary_keys:
    - ScrapReasonID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)

 - table: TransactionHistory
   primary_keys:
    - TransactionID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
  
 - table: TransactionHistoryArchive
   primary_keys:
    - TransactionID
   delta_keys:
    - ModifiedDate
   custom_casts:
    ModifiedDate: CONVERT(NVARCHAR(MAX), ModifiedDate, 121)
